### ISSUE TITLE
Rat King’s Crew quest is missing final content line below progression bar

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-commander-bugs#295]
![5395900f-f976-400a-b799-da20916843bd](https://user-images.githubusercontent.com/92684/31851555-df940af2-b61c-11e7-8dbe-975aa7ee3bc3.jpeg)
![8d5a323c-37fd-4e33-88fc-84779ea9311a](https://user-images.githubusercontent.com/92684/31851556-dfb0ab1c-b61c-11e7-8c88-6361a1c51cce.png)

**Comment by designker** [comment]
bungie don't provide that

**Comment by designker** [comment]
Actually they do

**Comment by NigelHietala** [comment]
Fixed long ago
