### ISSUE TITLE
Certain weapons in Postmaster don't show stat graphs

### ISSUE THREAD

**Issue by alexxnz** [NigelHietala/ishtar-commander-bugs#324]
From my testing, this only affects submachine guns and grenade launchers (the only weapon type I was unable to verify are rocket launchers, so maybe they should be checked too). Armor seems unaffected.

If these weapon types are in the Postmaster, viewing their stats, will not show the stat graphs for impact, range, etc. (see below)

Beta 140

![asset](https://user-images.githubusercontent.com/16849366/32687336-e93ac5c0-c687-11e7-98bb-a1d31023b6cb.PNG)

**Comment by floatingatoll** [comment]
@alexxnz is this fixed for you?

**Comment by NigelHietala** [comment]
Fixed
