### ISSUE TITLE
Double tap fails but moves to another character if active

### ISSUE THREAD

**Issue by netniV** [NigelHietala/ishtar-commander-bugs#327]
When you double tap an item, it attempts to transfer before stating that the item was not found.  However, if your active character is not the first character, Ishtar then shows this in the active character's inventory column.

Should the inventory always be shown against the active character?

**Comment by netniV** [comment]
![image](https://user-images.githubusercontent.com/9052188/32830150-36fb683e-c9ec-11e7-8be8-7d4dbe805ea0.png)

**Comment by netniV** [comment]
#266 is related

**Comment by netniV** [comment]
Is this still an active problem? Just wondering as it's in my list of open issues.

**Comment by designker** [comment]
it has yet to be fixed

**Comment by NigelHietala** [comment]
Fixed
