### ISSUE TITLE
All 1st Pg Lore Books Illegible

### ISSUE THREAD

**Issue by w1ckedartem1s** [NigelHietala/ishtar-commander-bugs#377]
Hello, all the first pages of each lore books in the Triumphs section is illegible. Gave an example(s) in photo attachment. Please resolve. 
Version 4.0.1
![1DCA7D83-E41C-480D-9C1E-C26EE087030E](https://user-images.githubusercontent.com/78748466/107247272-b5543c80-69f6-11eb-8cf4-614b69fbce95.png)
![A421D1E9-42FA-4870-9E04-63AF5F734613](https://user-images.githubusercontent.com/78748466/107247277-b5ecd300-69f6-11eb-8f34-4a2ad683b97f.png)

**Comment by NigelHietala** [comment]
Fixed in 4.0.3
