### ISSUE TITLE
Triumphs home page confused on iPad

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-commander-bugs#379]
![image](https://user-images.githubusercontent.com/92684/112759454-e6d59700-8fa7-11eb-8375-6290ac2ef115.png)

![image](https://user-images.githubusercontent.com/92684/112759457-e9d08780-8fa7-11eb-97c3-5b6463de7e56.png)

**Comment by NigelHietala** [comment]
Fixed awhile back
